[tool.black]
line-length = 100
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.pylint.messages_control]
disable = "C0111,R0903,C0103"

[tool.pylint.format]
max-line-length = "100"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"

[tool.bandit]
exclude_dirs = ["tests", "docs", ".github"]
# Skip assert check in test files
skips = ["B101"]
